### PR TITLE
Add initial Helm chart for the Brave exemplar service

### PR DESCRIPTION
**Pull request by yakca**
Initial Helm chart for the Brave to be used by Rancher

### CODE REVIEW

**Comment by philipnbbc** [comment]
I tried deploying another instance (in the same namespace) using the Rancher Web API and it didn't seem work - a new App was visible in the UI (with the name as set in the form) but no new workload was created.

A new workload was created when selecting a different namespace, but it was still called `brave` like the existing app in the `default` namespace.

I think the issue is that the name in the Helm chart is fixed to be `brave`. This means it can only be deployed once per namespace. It doesn't seem right to have to use a new namespace for each instance of brave.

**Comment by philipnbbc** [comment]
Another aspect I'm not sure about when discovering the endpoints is knowing which randomly selected port corresponds to the API (5000) or TCP output (7000). Hopefully there is a way to attach a label to the `publicEndpoint` that allows it to be associated with the `containerPort`.

The API provides the following info for the brave workload:
```json
"publicEndpoints": [
    {
        "addresses": [
            "34.242.252.60"
        ],
        "allNodes": true,
        "ingressId": null,
        "nodeId": null,
        "podId": null,
        "port": 32487,
        "protocol": "TCP",
        "serviceId": "default:brave"
    },
    {
        "addresses": [
            "34.242.252.60"
        ],
        "allNodes": true,
        "ingressId": null,
        "nodeId": null,
        "podId": null,
        "port": 31244,
        "protocol": "TCP",
        "serviceId": "default:brave"
    },
    {
        "addresses": [
            "34.242.252.60"
        ],
        "allNodes": true,
        "hostname": "brave.default.34.242.252.60.xip.io",
        "ingressId": "default:brave",
        "nodeId": null,
        "podId": null,
        "port": 80,
        "protocol": "HTTP",
        "serviceId": "default:brave"
    }
],
```

**Comment by yakca** [comment]
I've added dynamic naming, allowing multiple Brave apps per namespace when using a unique name per instance. 

On port discovery, hitting the `/services` endpoint for the app does allow us to identify services and ports used by name: 
```json
[
    {
        "name": "api",
        "nodePort": 31924,
        "port": 5000,
        "protocol": "TCP",
        "targetPort": 5000,
        "type": "/v3/project/schemas/servicePort"
    },
    {
        "name": "output",
        "nodePort": 30064,
        "port": 7000,
        "protocol": "TCP",
        "targetPort": 7000,
        "type": "/v3/project/schemas/servicePort"
    }
]
```

**Review by philipnbbc — APPROVED** [review]
LGTM and I tested it works.

**Pull request merged**
